#!/bin/bash

while true; do

    echo "Меню:"
    echo "1. Запустить редактор nano"
    echo "2. Запустить редактор vi"
    echo "3. Запустить браузер links"
    echo "4. Выход"

    read -p "Введите номер пункта меню: " choice

    case $choice in
        1)
            nano  # Запустить редактор nano
            ;;
        2)
            vi  # Запустить редактор vi
            ;;
        3)
            links  # Запустить браузер links
            ;;
        4)
            echo "Выход из меню"
            break  # Выход из цикла
            ;;
        *)
            echo "Ошибка: неверный номер пункта меню"
            ;;
    esac

    echo
done
