#!/bin/bash

terminate() {
  echo "TERM сигнал получен!"
  kill -TERM $handler_pid
  exit 0
}

handle_signal() {
  case $1 in
    USR1)
      echo "Получен сигнал USR1"
      kill -s USR1 $handler_pid
      ;;
    USR2)
      echo "Получен сигнал USR2"
      kill -s USR2 $handler_pid
      ;;
    *)
      echo "Некорректный сигнал"
      ;;
  esac
}

trap "terminate" SIGTERM

while read -r line; do
  case $line in
    "+")
      handle_signal USR1
      ;;
    "*")
      handle_signal USR2
      ;;
    "TERM")
      terminate
      ;;
  esac
done
